---
name: jagsa
description: Just another game streaming app
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get: ^3.17.1
  dio: ^3.0.10
  cached_network_image: ^2.3.3
  intl: ^0.16.1
  duration: ^2.0.15
  flag: ^3.1.0
  google_fonts: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
